# Generated by Django 2.2.1 on 2019-05-21 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='project_name',
        ),
        migrations.AddField(
            model_name='projectname',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time_app.Client'),
        ),
        migrations.AddField(
            model_name='timepost',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time_app.ProjectName'),
        ),
    ]
